### ISSUE TITLE
Multiple Chime Meeting Windows Launched

### ISSUE THREAD

**Issue by abhineet-bansal** [nachmore/ChimeHelper#1]
This is not a bug, but a usability improvement.

The delay between clicking and launching Chime meeting prompts multiple clicks. The multiple clicks are also prompted by the fact that the click doesn't have a clicked feedback (did the click work or it didn't?). So I end up with multiple Chime windows for joining the meeting.

The meeting link should be disabled for a fixed duration (500ms?). Or the link click should have some click feedback. Or both.

**Comment by nachmore** [comment]
Unfortunately the overall delay is the amount of time it takes Chrome to validate the pin and show some kind of UI (either the connect dialog or the "meeting not found" message). I had considered some kind of short animation ("chime loading") when clicking on a link to avoid the confusion of "click link -> dialog closed -> nothing happens for a while -> suddenly Chime pops up" but wasn't sure of the value.

For now, we'll try just forcing the popup to disappear when an item is clicked and see if that is helpful / not too confusing!

**Comment by nachmore** [comment]
Confirmed fixed :)
