### ISSUE TITLE
Recurrent Meeting not picked up

### ISSUE THREAD

**Issue by ldpamzn** [nachmore/ChimeHelper#2]
Hi, I have a recurrent meeting with Chime pin in Outlook, which has not been picked up by the helper. It's a daily 10 min standup meeting on my personal chime conf, happening in the next hour. Not sure what else I can provide to troubleshoot.

**Comment by nachmore** [comment]
Thanks for the report! Are you running the latest version [1.2](https://github.com/nachmore/AmazonChimeHelper/releases/tag/v1.2)? If not, please try on that version as that included multiple fixes.

If it is still occurring on 1.2 then can you please paste (or send me privately) a sanitized (i.e. replace chime bridge numbers with the fake numbers) copy of the meeting text and location? Also, are other meetings being picked up, just not this one? Thanks!

**Comment by nachmore** [comment]
Please feel free to reopen if this is still occurring...
