### ISSUE TITLE
Provide an option for Chime Helper to auto-dial into meetings

### ISSUE THREAD

**Issue by ATXDude** [nachmore/ChimeHelper#4]
Today, meetings routinely scheduled on Macs do not have enough of the prerequisites filled out for auto-dialing. This often happens when the invitee list is a mailing list, or chime meeting logistics is generated outside of outlook. On average, 50% of my meetings fall in this category. 
ChimeHelper does a great job of showing all my meetings regardless of how they were set up. It would be extremely helpful for users to have an "Auto-dial my meetings" option to select. It can be on a per meeting basis or a global option. The only conflict is that some of the meetings autodial themselves when set up with certain pre-requisites. Obviously, it would be not advisable to have Chime and ChimeHelper both autodial at different times for the same meeting. 

Thanks, appreciate any help in this direction.

**Comment by ATXDude** [comment]
Even a pop-up a few seconds before the meeting that says “Would you like to join your next meeting - <chime link>?”  would be super helpful.

**Comment by nachmore** [comment]
I currently have a build with this working (feel free to ping me for a private drop if you'd like to play around with it).

Would you want a sound / ring tone when it pops up?

**Comment by ATXDude** [comment]
Yeah, I would be glad to help test it out. Thanks a ton for putting this
together.
And yes, a ring tone would be fantastic. I have always loved the Mission
Impossible theme :) but I believe you should be the one to choose...

**Comment by nachmore** [comment]
Forgot to ping that this was released officially with https://github.com/nachmore/AmazonChimeHelper/releases/tag/v2.2 . Please let me know if it meets your needs :)

**Comment by ATXDude** [comment]
Fantastic. I will check it out and provide feedback. Much thanks for
following up and making this release.
